on: push

jobs:
  docker:
    runs-on: windows-2019
    steps:
    - 
      name: Build image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: false
        tags: user/app:latest
